const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{bgArtboard: 0},
	{Bullet: 0},
	{Tween: 0},
	{nest: 0},
	{Platform: 0},
	{ball: 0},
	{Solid: 0},
	{Sprite: 0},
	{Touch: 0},
	{nestX: 0},
	{Sprite2: 0},
	{lose: 0},
	{nestDestroyer: 0},
	{retry: 0},
	{play: 0},
	{lightAsset: 0},
	{menuScreenAssetsEffectsAsset: 0},
	{menuScreenAssetsEffectsAsset2: 0},
	{cloud: 0},
	{Sine: 0},
	{menuScreenAssetsEffectsAsset3: 0},
	{menuScreenAssetsEffectsAsset4: 0},
	{menuScreenAssetsEffectsAsset5: 0},
	{blackScreenAsset: 0},
	{TRYAGAINAssetsAsset: 0},
	{home: 0},
	{TRYAGAINAssetsAsset3: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{soundAsset: 0},
	{Audio: 0},
	{howToPlay: 0},
	{buttonAsset: 0},
	{time_passed: 0},
	{nest_create_X_index: 0},
	{score: 0},
	{h_score: 0},
	{sound: 0}
];

self.InstanceType = {
	bgArtboard: class extends self.ISpriteInstance {},
	nest: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	nestX: class extends self.IArrayInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	lose: class extends self.ISpriteInstance {},
	nestDestroyer: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	lightAsset: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset2: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset3: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset4: class extends self.ISpriteInstance {},
	menuScreenAssetsEffectsAsset5: class extends self.ISpriteInstance {},
	blackScreenAsset: class extends self.ISpriteInstance {},
	TRYAGAINAssetsAsset: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	TRYAGAINAssetsAsset3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	soundAsset: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	howToPlay: class extends self.ISpriteInstance {},
	buttonAsset: class extends self.ISpriteInstance {}
}